### ISSUE TITLE
Remove the file request.

### ISSUE THREAD

**Issue by dvaoru** [lvyitian/public_personal_files#2]
Hello.
I'm the developer of the Mock Locations app.
Today you posted a copy of my application to your repository.
I'm fine with app hacking and consider it an honor to have my apps hacked.
But this file has an API key and I have a problem with Google because this key is on Github.
Could you please remove this file from Github:
 https://github.com/lvyitian/public_personal_files/blob/fed0331087c21f6c249f651ffc5696200e52875c/Mock%20Locations%20v1.20.2%20%28Premium%29.apk

Best wishes,
Dvaoru

**Comment by lvyitian** [comment]
It has been removed from the latest commit now.
